### ISSUE TITLE
DB init is failing in our migration step from 2.34.5 to 2.35.1

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#667] opened 2019-05-13 13:11 UTC
Dears,

I have an issue in migrating to newer version of ONTRACK 2.35.1 . 
Issue was caused by: org.h2.jdbc.JdbcSQLException: Column "SEARCHKEY" contains null values; SQL statement:
ALTER TABLE PROPERTIES ALTER COLUMN SEARCHKEY VARCHAR(600) NOT NULL [90081-197]
        at org.h2.engine.SessionRemote.done(SessionRemote.java:623)
        at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:237)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        
I felt that we might have data with null in our past db and now its possible as you fixed as   #639 ticket. 
Could you please check it and if any concerns please revert to me ?

**Comment by DavidCADanneels** [comment] 2019-05-14 09:29
@dcoraboeuf do we need to follow a certain migration path?

**Comment by DavidCADanneels** [comment] 2019-05-14 09:39
I found this: https://github.com/nemerosa/ontrack/commit/ddcdce4a7751fd13c34b987cadc947f579501e2f#diff-43d980e2b9abf7cc27bac28a94afd5b0 executing:
`ALTER TABLE PROPERTIES DROP COLUMN SEARCHKEY;`
Perhaps we also need to drop that column first

**Comment by DavidCADanneels** [comment] 2019-05-14 09:45
The commit I was referring to was on the 3.38 branch
Perhaps the db/migration/V22__639_no_search_key.sql file was not added on the 2.35 branch.

**Comment by raj333921** [comment] 2019-05-14 09:46
I see in 2.35 it increases the size of coloumn to 200 but not removed !!

**Comment by DavidCADanneels** [comment] 2019-05-14 10:06
Nevermind my previous comments. I had a look at the code base and saw that
- this `ontrack-database` module only exists in 3.38, not in 2.35
- the script to drop the table was only added in 3.38
- in 2.35 another SQL file was added:
```
-- 41. Increase property search key max length (#639)

ALTER TABLE PROPERTIES ALTER COLUMN SEARCHKEY VARCHAR(600) NOT NULL;
```
Not only the search key is extended, also a `NON NULL` constraint is added.

**Comment by dcoraboeuf** [comment] 2019-05-14 16:39
* PR merged
* Waiting for release 2.35.2 to be created

**Comment by DavidCADanneels** [comment] 2019-05-14 17:51
@dcoraboeuf It seems that the merge resulted in some failing tests on your Jenkins instance (Travis tests are ok), but I see you are still working on this 2.35 branch.
Thanks for picking this up so quickly.

**Comment by dcoraboeuf** [comment] 2019-05-14 17:52
Yes, see PM in https://gitter.im/DavidCADanneels - I have infra issues currently (working on it)

**Comment by DavidCADanneels** [comment] 2019-05-14 17:58
Allright, I just checked it on my phone, since this site is not reachable from my Workstation ... What did you expect ... :)

**Comment by dcoraboeuf** [comment] 2019-05-14 18:17
Release 2.35.2 available. @raj333921  and @DavidCADanneels , can you test? And thanks for the contribution.

**Comment by DavidCADanneels** [comment] 2019-05-14 19:02
After upgrade our dependency to Ontrack version 2.35.2 I was able to release a new version of our Ontrack Extension.
I'm currently trying to deploy this Ontrack (+ Extention) in our Jenkins Repetion Environment, but the health check on the container still fails (it ran much longer than before)
@raj333921 We need to check the logs to see what was the error. And perhaps log in to the container during the deployment to follow up there.

**Comment by raj333921** [comment] 2019-05-14 19:23
I will check it tommorow I am outside

**Comment by DavidCADanneels** [comment] 2019-05-14 22:00
The issue is fixed: I had to update the version in **two** places. Release and Deployment succeeded.
@dcoraboeuf you can close this ticket.

**Closed** 2019-05-16 08:21 UTC
Labels: bug, h2, v2
